apiVersion: v1
kind: Secret
metadata:
  name: donation-service-secrets
  namespace: donation-service
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@donation-db.c69c2yweoc4n.us-east-1.rds.amazonaws.com:5432/donation_db"